stages:
  - validate
  - plan
  - deploy

default:
  tags:
    - docker
  image: 
    name: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  variables:
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/aws-buckets

terraform-fmt:
  stage: validate
  before_script:
    - cp .terraformrc ~/
  script:
    - terraform fmt -check -recursive

terraform-validate:
  stage: validate
  before_script:
    - cp .terraformrc ~/
  script:
    - gitlab-terraform init; gitlab-terraform validate

terraform-plan:
  stage: plan
  before_script:
    - cp .terraformrc ~/
  script:
    - gitlab-terraform plan

deploy:
  stage: deploy
  before_script:
    - cp .terraformrc ~/
  script:
    - gitlab-terraform apply