stages:
  - validate
  - plan
  - deploy

default:
  tags:
    - docker

terraform-validate:
  stage: validate
  image: hashicorp/terraform:1.5
  entrypoint: ["/bin/sh", "-c"]
  before_script:
    - terraform --version
    - init
  script:
    - validate

terraform-plan:
  image: hashicorp/terraform:1.5
  stage: plan
  before_script:
    - init
  script:
    - plan