stages:
  - validate
  - plan
  - deploy
  - destroy

.base-terraform:
  tags:
    - docker
  image: 
    name: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  variables:
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/aws-buckets

terraform-validate:
  stage: validate
  extends: .base-terraform
  before_script:
    - cp .terraformrc ~/
  script:
    - gitlab-terraform init; gitlab-terraform validate

terraform-plan:
  stage: plan
  extends: .base-terraform
  before_script:
    - cp .terraformrc ~/
  script:
    - gitlab-terraform plan
    - gitlab-terraform show -json plan.cache > plan.json
  artifacts:
    expire_in: 1 day
    paths:
      - plan.cache
      - plan.json

deploy:
  stage: deploy
  extends: .base-terraform
  before_script:
    - cp .terraformrc ~/
  script:
    - gitlab-terraform apply

destroy:
  stage: destroy
  extends: .base-terraform
  before_script:
    - cp .terraformrc ~/
  script:
    - gitlab-terraform destroy
  dependencies:
    - deploy
  when: manual