stages:
  - validate
  - plan
  - deploy

default:
  tags:
    - docker
  image: 
    name: hashicorp/terraform:1.5
    entrypoint: ["/bin/sh", "-c"]

terraform-validate:
  stage: validate
  before_script:
    - cp .terraformrc ~/
  script:
    - terraform init
    - terraform validate

terraform-plan:
  stage: plan
  before_script:
    - cp .terraformrc ~/
  script:
    - terraform init
    - terraform plan