stages:
  - validate
  - plan
  - deploy

default:
  image: hashicorp/terraform:1.5
  tags:
    - docker

terraform-validate:
  stage: validate
  before_script:
    - terraform init
  script:
    - terraform validate

terraform-plan:
  stage: plan
  before_script:
    - terraform init
  script:
    - terraform plan