stages:
  - validate
  - plan
  - deploy

default:
  tags:
    - docker
  image: 
    name: hashicorp/terraform:1.5
    entrypoint: ["/bin/sh", "-c"]

terraform-validate:
  stage: validate
  before_script:
    - cp .terraformrc ~/
  script:
    - terraform init
        -migrate-state
        -backend-config=address=${TF_ADDRESS}
        -backend-config=username=${TF_USERNAME}
        -backend-config=password=${TF_PASSWORD}
    - terraform validate

terraform-plan:
  stage: plan
  before_script:
    - cp .terraformrc ~/
  script:
    - terraform init
    - terraform plan

deploy:
  stage: deploy
  before_script:
    - cp .terraformrc ~/
    - terraform init
  script:
    - terraform apply -auto-approve