stages:
  - validate
  - plan
  - deploy

default:
  tags:
    - docker

terraform-validate:
  stage: validate
  image: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
    - terraform --version
    - init
  script:
    - validate

terraform-plan:
  image: hashicorp/terraform:1.5
  stage: plan
  before_script:
    - init
  script:
    - plan